import "./globals.css";

// remote font import
import { Playwrite_AU_QLD } from "next/font/google";

// local font import
import LocalFont from "next/font/local";

// remote font kurulum
const playwrite = Playwrite_AU_QLD({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-play",
});

// local font kurulum
const crack = LocalFont({
  src: "../assets/Crackajack.ttf",
  variable: "--font-crack",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${playwrite.variable} ${crack.variable}`}>
        <main className="p-20 text-4xl">{children}</main>
      </body>
    </html>
  );
}
