const users = [
  {
    id: 1,
    name: "Ali",
    surname: "Kaya",
    age: 28,
    adress: { city: "Ankara", cityNo: 6 },
    hobbies: ["Futbol", "Satranç"],
  },
  {
    id: 2,
    name: "Zeynep",
    surname: "Demir",
    age: 22,
    adress: { city: "İzmir", cityNo: 35 },
    hobbies: ["Resim", "Yazılım"],
  },
  {
    id: 3,
    name: "Mehmet",
    surname: "Yılmaz",
    age: 30,
    adress: { city: "Bursa", cityNo: 16 },
    hobbies: ["Müzik", "Kamp"],
  },
  {
    id: 4,
    name: "Ayşe",
    surname: "Şahin",
    age: 26,
    adress: { city: "Antalya", cityNo: 7 },
    hobbies: ["Yoga", "Fotoğrafçılık"],
  },
  {
    id: 5,
    name: "Emre",
    surname: "Koç",
    age: 32,
    adress: { city: "Konya", cityNo: 42 },
    hobbies: ["Basketbol", "Oyun"],
  },
  {
    id: 6,
    name: "Elif",
    surname: "Öztürk",
    age: 24,
    adress: { city: "Eskişehir", cityNo: 26 },
    hobbies: ["Tiyatro", "Kitap"],
  },
  {
    id: 7,
    name: "Hasan",
    surname: "Güneş",
    age: 40,
    adress: { city: "Trabzon", cityNo: 61 },
    hobbies: ["Balıkçılık", "Gezmek"],
  },
  {
    id: 8,
    name: "Merve",
    surname: "Çelik",
    age: 27,
    adress: { city: "Adana", cityNo: 1 },
    hobbies: ["Dans", "Yüzme"],
  },
  {
    id: 9,
    name: "Burak",
    surname: "Arslan",
    age: 29,
    adress: { city: "Gaziantep", cityNo: 27 },
    hobbies: ["Kodlama", "Futbol"],
  },
  {
    id: 10,
    name: "Ceren",
    surname: "Karaca",
    age: 23,
    adress: { city: "Samsun", cityNo: 55 },
    hobbies: ["Müzik", "Gezi"],
  },
  {
    id: 11,
    name: "Hakan",
    surname: "Aydın",
    age: 31,
    adress: { city: "Mersin", cityNo: 33 },
    hobbies: ["Kamp", "Satranç"],
  },
  {
    id: 12,
    name: "Gizem",
    surname: "Bulut",
    age: 25,
    adress: { city: "Malatya", cityNo: 44 },
    hobbies: ["Fotoğrafçılık", "Tasarım"],
  },
  {
    id: 13,
    name: "Furkan",
    surname: "Eren",
    age: 35,
    adress: { city: "Kayseri", cityNo: 38 },
    hobbies: ["Yazılım", "Futbol"],
  },
  {
    id: 14,
    name: "Deniz",
    surname: "Yıldırım",
    age: 28,
    adress: { city: "Edirne", cityNo: 22 },
    hobbies: ["Tiyatro", "Kamp"],
  },
  {
    id: 15,
    name: "Selin",
    surname: "Koçak",
    age: 26,
    adress: { city: "Muğla", cityNo: 48 },
    hobbies: ["Yoga", "Resim"],
  },
  {
    id: 16,
    name: "Berk",
    surname: "Şen",
    age: 33,
    adress: { city: "Kocaeli", cityNo: 41 },
    hobbies: ["Basketbol", "Film"],
  },
  {
    id: 17,
    name: "Aslı",
    surname: "Taş",
    age: 30,
    adress: { city: "Erzurum", cityNo: 25 },
    hobbies: ["Kitap", "Doğa"],
  },
  {
    id: 18,
    name: "Ömer",
    surname: "Demirtaş",
    age: 29,
    adress: { city: "Sivas", cityNo: 58 },
    hobbies: ["Kamp", "Teknoloji"],
  },
  {
    id: 19,
    name: "Ece",
    surname: "Acar",
    age: 27,
    adress: { city: "Denizli", cityNo: 20 },
    hobbies: ["Dans", "Gezmek"],
  },
  {
    id: 20,
    name: "Serkan",
    surname: "Yalçın",
    age: 34,
    adress: { city: "Van", cityNo: 65 },
    hobbies: ["Müzik", "Kodlama"],
  },
];

export default users;
